# Generated by Django 5.2 on 2025-04-24 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='quotes.faculties')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('reposts_count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.professors')),
            ],
        ),
        migrations.CreateModel(
            name='QuotesProfessorRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(blank=True, null=True)),
                ('professor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_ref', models.ForeignKey(blank=True, db_column='faculty_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.faculties')),
            ],
            options={
                'db_table': 'quotes_professors_raw',
            },
        ),
    ]
