# Generated by Django 5.2 on 2025-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
