# Generated by Django 5.2 on 2025-04-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professors',
            options={},
        ),
    ]
