# Generated by Django 5.2 on 2025-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_professors_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
