# Generated by Django 5.2 on 2025-04-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_authgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(blank=True, null=True)),
                ('professor', models.CharField(blank=True, null=True)),
                ('faculty', models.CharField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('reposts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raw_data',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='professors',
            name='date',
        ),
        migrations.RemoveField(
            model_name='professors',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='professors',
            name='reposts',
        ),
        migrations.AddField(
            model_name='professors',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quotes.faculties'),
        ),
        migrations.AlterModelTable(
            name='professors',
            table=None,
        ),
    ]
