# Generated by Django 5.2 on 2025-04-08 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rawdata_alter_authgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotesProfessors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(blank=True, null=True)),
                ('professor', models.CharField(blank=True, null=True)),
                ('faculty', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quotes_professors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, null=True)),
                ('likes_count', models.IntegerField(blank=True, null=True)),
                ('reposts_count', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
        migrations.AlterModelOptions(
            name='professors',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='quotes',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quotes.professors'),
        ),
    ]
